version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /mnt/efs:/mnt/efs:ro # use mount as read-only
    environment:
      - VIT_MODEL_PATH=/mnt/efs/mhist_vit_f1_dynamo_model.onnx
    restart: unless-stopped