name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t flask_files-web flask_files
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push flask_files-web:latest
      
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_RSA_KEY }} # private SSH key
          HOST: ${{ secrets.EC2_SERVER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key docker-compose.yml ec2-user@${HOST}:/home/ubuntu/histology-image-analysis/flask_files/docker-compose.yml
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${HOST} '
            cd /home/ubuntu/histology-image-analysis/flask_files
            docker-compose pull
            docker-compose up -d
          '