name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Add GitHub Actions IP to Security Group
        run: |
          SECURITY_GROUP_ID="sg-01fefb330f6147653"
          IP=$(curl -s https://api.ipify.org)
          aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 22 --cidr $IP/32

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_RSA_KEY }}
          HOST: ${{ secrets.EC2_SERVER }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ls -l private_key  # Debug: Check file permissions
          ssh-keygen -y -f private_key  # Debug: Verify key is valid
          scp -o StrictHostKeyChecking=no -i private_key -r ./* ${USER}@${HOST}:/home/ubuntu/histology-image-analysis/flask_files/
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd /home/ubuntu/histology-image-analysis/flask_files/
            docker-compose build
            docker-compose up -d
          '

      - name: Remove GitHub Actions IP from Security Group
        if: always()
        run: |
          SECURITY_GROUP_ID="sg-01fefb330f6147653"
          IP=$(curl -s https://api.ipify.org)
          aws ec2 revoke-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 22 --cidr $IP/32
