name: Deploy Lambda Function

on:
  push:
    branches:
      - main

env:
    AWS_REGION: us-west-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # checkout the commit that triggered this action

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: docker build --platform linux/amd64 -t fake-news-docker docker_image_files

    # This will get the 'registry' URI from output from the action: steps.login-ecr
    # The ECR URI contains the account number, with the syntax: 123456789012.dkr.ecr.us-west-1.amazonaws.com
    - name: Tag Docker Images
      run: docker tag fake-news-docker:latest ${{ steps.login-ecr.outputs.registry }}/fake-news-model:latest

    - name: Push Docker Image to ECR
      run: docker push ${{ steps.login-ecr.outputs.registry }}/fake-news-model:latest

    - name: Update Lambda Function
      run: aws lambda update-function-code --function-name predict-fake-news --region us-west-1 --image-uri ${{ steps.login-ecr.outputs.registry }}/fake-news-model:latest
